#!/usr/bin/env bash
set -euo pipefail

repo=jokereph
image="$repo"/mlir-tutorial:debug

quoted_args=""
if [ "$#" -gt 0 ]; then
    quoted_args=$(printf '%q ' "$@")
    quoted_args=${quoted_args//\\|/|}
    quoted_args=${quoted_args% }   # remove trailing space
fi

# Note that this limits commands to non quoted arguments, would require re-quoting...
exec docker run --rm -it -v "$PWD:/tmp/tutorial" -w "/tmp/tutorial" "$image" bash -c \
  "$quoted_args"
